### PR TITLE
Python example of listing IOCs

### PR DESCRIPTION
**Pull request by kasemir**
Example of looping over every channel, cataloging IOCs and host

### CODE REVIEW

**Comment by shroffk** [comment]
We could in the future try to update the script to use scroll instead of search to ensure that we get consistent responses.

**Comment by kasemir** [comment]
I think "scroll" refers to the "from" and "size" parameters and per se seems deprecated.
From https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#scroll-search-results : 

```We no longer recommend using the scroll API for deep pagination. If you need to preserve the index state while paging through more than 10,000 hits, use the [search_after](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after) parameter with a point in time (PIT)```

I got as far as using search-after, which can run through 500k channels. I did not add the PIT to 'lock' the result, so yes, in case of concurrent modifications, you might see some of them and not others.

**Comment by shroffk** [comment]
Oh.
I had missed that scrolling was deprecated...thanks for pointing it out

**Comment by kasemir** [comment]
It's a little worrisome how rapidly ES is evolving. Our 'mapping' definitions changed from 6 to 7 and don't work with 8 at all, the cursor handling changes, ... Those new features may be great for cutting edge users, but for our channel finder and alarm log, elastic is a comparably simple data store. It should just "work", not require us to tweak our code every 2 years.  Compare to Oracle/MySQL/Postgres which have been very static in the last 20 years.

**Comment by shroffk** [comment]
I kind of agree... seems like there should be some middle ground.
I feel like mongo could be the answer but it has updates too.

**Pull request merged**
